# Numpy and Xarray

Most neuroscience data ends up as a multidimensional array at some point: a recording with samples and channels, an image stack with pixels and time, or a tensor of trials, conditions, and time points. This homework session introduces the two array libraries:

- **NumPy** provides the n-dimensional array (`ndarray`) and the vectorised operations that work on it.
- **Xarray** builds on top of NumPy by attaching *names*, *coordinates*, and *metadata* to each axis, so that you can refer to dimensions and indices by meaning rather than by position.

## Setup

### Import Libraries

In [2]:
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
from pathlib import Path

<a target="_blank" href="https://colab.research.google.com/github/ANDA-NI-2026/NI-Day2-Data-Models/blob/main/01_homework/01_exercises.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

## NumPy Arrays

### Background

Numpy can be used to store data of the same type together in array. Compared to plain Python lists, arrays are more memory-efficient and faster for numerical work. An array has a fixed `shape` (the size of each dimension) and a `dtype` (the type of element stored), and supports slicing and arithmetic along chosen axes of your array. In this section you will learn different ways of creating arrays, how to access specific columns, rows, or elements with slicing, and how to perform mathematical operations on the data in your array.

### Exercises

| Code | Description |
| :-- | :-- |
| `np.linspace(0, 1, 10)` | 10 evenly spaced values between 0 and 1 (inclusive). |
| `np.random.uniform(0, 1, size=10)` | 10 random numbers drawn uniformly between 0 and 1. |
| `np.zeros(8)` | Create a 1-D array of length 8 filled with zeros. |
| `np.zeros((2, 3))` | Create a 2x3 array filled with zeros. |
| `np.ones(n)` | Create an array of length `n` filled with ones. |
| `a.shape` | Inspect the array shape (the size of each dimension). |
| `a[0]`, `a[:, 1]` | Select a row, or select a column with `:` along one axis. |
| `a.mean(axis=1)`, `a.mean(axis=0)`, `a.mean()` | Average along a chosen axis, or over all elements. |

**Example**: Create an array containing 10 evenly spaced points from 0 to 1.

In [3]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**Exercise**: Create an array containing 100 evenly spaced points from 0 to 2.

In [18]:
np.linspace(0, 2, 100)

array([0.        , 0.02020202, 0.04040404, 0.06060606, 0.08080808,
       0.1010101 , 0.12121212, 0.14141414, 0.16161616, 0.18181818,
       0.2020202 , 0.22222222, 0.24242424, 0.26262626, 0.28282828,
       0.3030303 , 0.32323232, 0.34343434, 0.36363636, 0.38383838,
       0.4040404 , 0.42424242, 0.44444444, 0.46464646, 0.48484848,
       0.50505051, 0.52525253, 0.54545455, 0.56565657, 0.58585859,
       0.60606061, 0.62626263, 0.64646465, 0.66666667, 0.68686869,
       0.70707071, 0.72727273, 0.74747475, 0.76767677, 0.78787879,
       0.80808081, 0.82828283, 0.84848485, 0.86868687, 0.88888889,
       0.90909091, 0.92929293, 0.94949495, 0.96969697, 0.98989899,
       1.01010101, 1.03030303, 1.05050505, 1.07070707, 1.09090909,
       1.11111111, 1.13131313, 1.15151515, 1.17171717, 1.19191919,
       1.21212121, 1.23232323, 1.25252525, 1.27272727, 1.29292929,
       1.31313131, 1.33333333, 1.35353535, 1.37373737, 1.39393939,
       1.41414141, 1.43434343, 1.45454545, 1.47474747, 1.49494

**Exercise**: Create an array containing 11 evenly spaced points from 0 to 10.

In [17]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

**Exercise**: Create an array containing 10 random numbers between 0 and 1.

In [16]:
np.random.rand(10)

array([0.15449605, 0.85723784, 0.69233169, 0.88456984, 0.896065  ,
       0.92203914, 0.35244615, 0.47896194, 0.34308189, 0.50069556])

**Exercise**: Create an array containing 10 random numbers between -5 and 5.

In [15]:
np.random.uniform(-5, 5, 10)

array([ 1.03543   , -3.8120227 , -0.36049727,  0.13158468, -1.5446271 ,
        2.20215349, -2.21442717,  0.31993366, -4.70484921,  2.01774926])

**Exercise**: Create an array of length `8` containing zeros.

In [14]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

**Exercise**: Create a 2D array of dimensions `(2, 3)` containing zeros.

In [13]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**Exercise**: Create a 2D array of dimensions `(4, 10)` containing zeros and assign it to a variable named `data`.

In [19]:
data = np.zeros((4, 10))

Run the cell below to create a 2D array named `data` with dimensions `(4,10)` containing numbers between 0's on the first row, 1's on the second row, 2's on the third row, and 3's on the third row.

In [20]:
data = np.zeros((4,10))
data[1, :] += np.ones(data.shape[1])
data[2, :] += 2*np.ones(data.shape[1])
data[3, :] += 3*np.ones(data.shape[1])
data

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

**Exercise**: Compute the mean of `data` across rows (axis 1). The result should contain 4 numbers.

In [22]:
row_means = np.mean(data, axis=1)
print(row_means)

[0. 0. 0. 0.]


**Exercise**: Compute the mean of `data` across columns (axis 0). The result should contain 10 numbers.

In [24]:
row_means = np.mean(data, axis=0)
print(row_means)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Exercise**: Compute the mean of all elements (no axis specification) in `data`. The result should be a single number.

In [25]:
overall_mean = np.mean(data)
print(overall_mean)

0.0


**Exercise**: Select the first row in `data`.

In [27]:
data[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Exercise**: Select the second row in `data`.

In [29]:
data[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Exercise**: Select the second *column* in `data`.

In [28]:
data[:, 1]

array([0., 0., 0., 0.])

## Intro to Working with Xarray

### Background

NumPy arrays are powerful but minimal: they store numerical data without any built-in information about what the axes represent. In scientific datasets, however, each axis usually corresponds to meaningful quantities such as space, time, wavelength, or experimental condition. When working with multidimensional data, it is often useful to label these dimensions explicitly.

**[Xarray](https://docs.xarray.dev/en/stable/user-guide/index.html)** extends NumPy by adding labels and metadata to multidimensional arrays. Each array can have named dimensions, coordinate values, and descriptive metadata attached to it. This makes many operations clearer and safer, since calculations can reference dimensions by name rather than by numeric index.

### Exercises

In this section you will create `DataArray`s from NumPy arrays, attach coordinates and metadata, and select data by name and by label.

| Code | Description |
| :-- | :-- |
| `xr.DataArray(data=a, dims=['channel', 'time'])` | Wrap a NumPy array `a` and name its axes. |
| `xr.DataArray(data=a, dims=['channel', 'time'], coords={'time': t, 'channel': ch}, name='eeg')` | Attach coordinate values and a variable name. |
| `da['time']` | Access the `time` coordinate. |
| `da.sel(channel='Cz')` | Select the data for a single named channel. |
| `da.sel(time=slice(0.5, 1.0))` | Select all samples whose `time` coordinate is between 0.5 and 1.0. |
| `da.sel(channel=['Cz', 'Fz'])` | Select two named channels at once. |
| `da.mean(dim='time')` | Reduce along a named dimension. |
| `da.attrs = {'units': 'uV'}` | Attach metadata describing the array. |
| `da.plot()` | Quick plot that uses dimension names and coordinates as axis labels. |

The exercises in this section introduce the core concepts of XArray: treating a DataArray like a NumPy array, labeling dimensions, attaching coordinates, and adding metadata to describe the data.

#### `xr.DataArray()` as a Numpy-Like Array

At its core, an XArray DataArray wraps a NumPy array. Most numerical operations that work on NumPy arrays also work on DataArray objects, including slicing, aggregation, and arithmetic. This means that existing NumPy-style code often requires very little modification to work with labeled arrays.

**Example**: Create a three-dimensional `DataArray` from a Numpy array:

In [30]:
da = xr.DataArray(
    data=np.random.random(size=(10, 20, 30))
)
da

<xarray.DataArray (dim_0: 10, dim_1: 20, dim_2: 30)> Size: 48kB
array([[[0.87428942, 0.48558094, 0.31832766, ..., 0.28452179,
         0.20523288, 0.11826896],
        [0.77414979, 0.23023134, 0.94404281, ..., 0.56368648,
         0.55750464, 0.15436082],
        [0.26919252, 0.55695437, 0.70547281, ..., 0.228736  ,
         0.38214431, 0.17946304],
        ...,
        [0.46764857, 0.31924095, 0.77717549, ..., 0.83607748,
         0.98324846, 0.00266546],
        [0.72569296, 0.5267178 , 0.8617363 , ..., 0.16540805,
         0.76278467, 0.43529964],
        [0.31229909, 0.29822073, 0.85478284, ..., 0.87291025,
         0.98976813, 0.64572338]],

       [[0.27135837, 0.83088365, 0.44688408, ..., 0.66042176,
         0.23727528, 0.30842506],
        [0.82818922, 0.2363696 , 0.13575008, ..., 0.65271052,
         0.53531946, 0.13606125],
        [0.94822671, 0.10133763, 0.24826454, ..., 0.69560636,
         0.83697024, 0.61472636],
...
        [0.686263  , 0.71887735, 0.4939752 , ..., 0.61784527,
         0.65852912, 0.52412516],
        [0.6404705 , 0.60702473, 0.9175823 , ..., 0.60246198,
         0.97183759, 0.81501782],
        [0.93212302, 0.47325153, 0.74334059, ..., 0.71025661,
         0.86115364, 0.77326563]],

       [[0.52051222, 0.11108865, 0.44161696, ..., 0.86676544,
         0.46346195, 0.20967551],
        [0.45600368, 0.430448  , 0.07421603, ..., 0.93458669,
         0.78659536, 0.85395772],
        [0.00744805, 0.39818314, 0.49126354, ..., 0.79409733,
         0.57063949, 0.51088359],
        ...,
        [0.14419975, 0.71655178, 0.92248447, ..., 0.01823223,
         0.05735447, 0.33477851],
        [0.67289579, 0.5286565 , 0.5240696 , ..., 0.03800404,
         0.73764045, 0.57632669],
        [0.63716187, 0.29020076, 0.73687847, ..., 0.46097362,
         0.06952275, 0.56870941]]])
Dimensions without coordinates: dim_0, dim_1, dim_2

**Exercise**: Select the first 5 rows of `da`, using the slicing syntax `x[:10, :, :]`

**Exercise**: Compute the mean, using either `DataArray.mean()` or `np.mean()`

**Exercise**: Compute the mean over the third axis, using `da.mean(axis=2)`

#### Labeling the Data and the Dimensions: `name=` and `dims=`

One of XArray’s most useful features is the ability to name dimensions explicitly. Instead of referring to axes by position—such as “axis 0” or “axis 2”—operations can refer to dimensions using meaningful labels like "x", "y", or "time".

Once dimensions are named, many operations become easier to read and harder to misuse. For example, computing the mean across time can be expressed as mean(dim="time"), which clearly communicates the intent of the calculation.

**Exercise**: Make a new `da` 3-dimensional array variable using `xr.DataArray()`, this time additionally setting `name="image"` and `dims=['x', 'y', 'time']`

In [31]:
da = xr.DataArray(
    data=0,
    coords={'x': range(4), 'y': range(5), 'time': range(3)},
    dims=['x', 'y', 'time'],
    name="image"
)

**Exercise**: Select the fourth time sample using `da.sel(time=4)`

**Exercise**: Select the first-through fifth rows by name using `da.sel(x=slice(0, 5))`

**Exercise**: Compute the Mean image over time by name, using `da.mean(dim='time')`:

**Exercise**: The time points are stored in the numpy array `t` below.  Use `mask = t > 40; da.sel(time=mask)` to select only the data corresponding to time points greater than 40:

In [ ]:
t = np.linspace(0, 100, 30)

#### Labeling each Axis using Coordinates and Attributes

Beyond naming dimensions, XArray allows each axis to have coordinate values that describe the physical meaning of each index. For example, a time axis might correspond to timestamps, or a spatial axis might correspond to pixel positions.

Coordinates make it possible to select data based on meaningful values rather than raw indices. For example, selecting frames after a particular time point can be done using coordinate values instead of computing index positions manually.

**Example**: Run the code below to make a new `da` using `xr.DataArray()`, this time additionally mapping the time axis to the time points themselves using `coords=`:

In [ ]:
da = xr.DataArray(
    data=np.random.random(size=(10, 20, 30)),
    name='image',
    dims=['x', 'y', 'time'],
    coords = {
        'time': np.linspace(0, 100, 30),
    }
)
da

<xarray.DataArray 'image' (x: 10, y: 20, time: 30)> Size: 48kB
array([[[0.66411211, 0.61321089, 0.77799478, ..., 0.60487832,
         0.81780103, 0.51288201],
        [0.26831084, 0.63951385, 0.38034877, ..., 0.47071095,
         0.87925474, 0.00362314],
        [0.34497752, 0.30109007, 0.19870258, ..., 0.81097008,
         0.32149049, 0.75546293],
        ...,
        [0.58388595, 0.88828119, 0.93670931, ..., 0.42529124,
         0.49929151, 0.95321901],
        [0.85108608, 0.95602829, 0.2411505 , ..., 0.70897086,
         0.62037308, 0.69338775],
        [0.7415936 , 0.87480223, 0.88257276, ..., 0.5234893 ,
         0.11571473, 0.57900377]],

       [[0.49932819, 0.84881593, 0.93799346, ..., 0.54651641,
         0.72238812, 0.83493695],
        [0.11300725, 0.79783991, 0.32710949, ..., 0.32200166,
         0.11574021, 0.20065044],
        [0.46674217, 0.34070847, 0.54560118, ..., 0.60935145,
         0.43398135, 0.6867824 ],
...
        [0.87345945, 0.97699416, 0.96727549, ..., 0.18244762,
         0.9027874 , 0.89820532],
        [0.56761519, 0.43132623, 0.33496028, ..., 0.0516507 ,
         0.13803519, 0.86534971],
        [0.16781826, 0.44200279, 0.565072  , ..., 0.34858964,
         0.54975653, 0.5794999 ]],

       [[0.9488494 , 0.58982013, 0.02506706, ..., 0.35110223,
         0.65866245, 0.76722738],
        [0.91342788, 0.53646346, 0.24423397, ..., 0.20540218,
         0.75934743, 0.36068679],
        [0.34346403, 0.22931287, 0.421505  , ..., 0.18898619,
         0.44425942, 0.09040306],
        ...,
        [0.81647878, 0.39724468, 0.19077025, ..., 0.78849692,
         0.09476013, 0.22739184],
        [0.28895769, 0.23754446, 0.19223474, ..., 0.72763705,
         0.23681852, 0.90540172],
        [0.00227439, 0.9606731 , 0.07978697, ..., 0.56400248,
         0.47624589, 0.87455739]]], shape=(10, 20, 30))
Coordinates:
  * time     (time) float64 240B 0.0 3.448 6.897 10.34 ... 93.1 96.55 100.0
Dimensions without coordinates: x, y

**Exercise**: Use `da.sel(time = slice(40, None))` to select only the data corresponding to time points greater than 40, without first creating a mask:

#### Adding Descriptions to the data

Support for basic data descriptions is quite extensive.  Things like units, long names for plotting, processing history, and even descriptions for explaining each part of the data are supported by adding the data to a dictionary attached to `xarray` objects called `attrs`. Some keys are recognized by other tooling (e.g. `units`, `description`, `long_name`), but for the most part, any kind of key-value combination is supported for metadata.

**Example**: Run the code below to create a new `da` DataArray using `DataArray`, this time with extra attributes describing the main variables.

In [ ]:
time = xr.DataArray(
    data = np.linspace(0, 100, 30),
    name = 'time',
    dims=['time'],
    attrs = {
        'units': 's',
        'description': 'time samples for each image frame'
    }
)

da = xr.DataArray(
    data=np.random.random(size=(10, 20, 30)),
    name='image',
    dims=['x', 'y', 'time'],
    coords = {
        'time': time,
    },
    attrs = {
        'units': 'brightness',
        'description': 'a generated random image stack',
        'long_name': 'calcium image pixel brightness',
    }
)
da

<xarray.DataArray 'image' (x: 10, y: 20, time: 30)> Size: 48kB
array([[[0.82354816, 0.52292853, 0.10666037, ..., 0.42289179,
         0.99782003, 0.49607635],
        [0.12985498, 0.12763057, 0.07046139, ..., 0.64814128,
         0.58234373, 0.12883534],
        [0.55022341, 0.34076009, 0.81538328, ..., 0.57887583,
         0.8056537 , 0.13388089],
        ...,
        [0.26854525, 0.53283331, 0.63230879, ..., 0.13280682,
         0.72024067, 0.71239432],
        [0.57303676, 0.19654853, 0.95910557, ..., 0.86204161,
         0.82693005, 0.73520056],
        [0.31431091, 0.33030612, 0.30249442, ..., 0.40123431,
         0.30194928, 0.351028  ]],

       [[0.38628946, 0.7558288 , 0.78802452, ..., 0.79105905,
         0.89664269, 0.65264137],
        [0.36112009, 0.78401218, 0.9242207 , ..., 0.49747566,
         0.98220942, 0.54447116],
        [0.78281561, 0.62245213, 0.3897531 , ..., 0.58020462,
         0.73119609, 0.10952419],
...
        [0.80265334, 0.53560826, 0.89920452, ..., 0.66503514,
         0.76782656, 0.31708577],
        [0.66716965, 0.6248026 , 0.78283432, ..., 0.94025448,
         0.15667577, 0.02134525],
        [0.38662875, 0.13445524, 0.60421954, ..., 0.69339363,
         0.79644892, 0.03368359]],

       [[0.74141697, 0.90176798, 0.77728334, ..., 0.13535366,
         0.13664637, 0.68282886],
        [0.1595881 , 0.70037268, 0.27823299, ..., 0.44081631,
         0.52533783, 0.58288148],
        [0.58639489, 0.9931304 , 0.19861053, ..., 0.4506233 ,
         0.2062197 , 0.79268328],
        ...,
        [0.53752456, 0.96575008, 0.46299236, ..., 0.45842997,
         0.05353041, 0.00610113],
        [0.99512609, 0.41493162, 0.43907269, ..., 0.23812992,
         0.56804535, 0.24241836],
        [0.75024963, 0.90986467, 0.980608  , ..., 0.91442848,
         0.91002944, 0.61638018]]], shape=(10, 20, 30))
Coordinates:
  * time     (time) float64 240B 0.0 3.448 6.897 10.34 ... 93.1 96.55 100.0
Dimensions without coordinates: x, y
Attributes:
    units:        brightness
    description:  a generated random image stack
    long_name:    calcium image pixel brightness

**Exercise**: View the attributes of the `da` DataArray with `da.attrs`

**Exercise**: View the attributes of the `time` coordinate on the `da` DataArray with `da.time.attrs`:

**Exercise**: Plot the mean pixel brightness over time and check that some attributes are used automatically in the plot, with `da.mean(dim=['x', 'y']).plot()`:

There are many, many more features that XArray provides to add convenience to an analysis, but this should be enough to get us started.

**Example**: Wrap a 2-D NumPy array of EEG-like data in a `DataArray` with named dimensions, coordinates, and a name.

**Exercise**: Get the `time` coordinate of the `eeg` DataArray.

**Exercise**: Select the channel labelled `'Cz'` using `.sel`.

**Exercise**: Select the data between 0.5 and 1.0 seconds for channels `'Fz'` and `'Cz'`.

**Exercise**: Compute the mean across time for every channel using the dimension name (not the axis number).

**Exercise**: Attach metadata so that `eeg` has `units = 'uV'` and `description = 'simulated EEG data'`, and the `time` coordinate has `units = 's'`. Then plot `eeg.sel(channel='Cz')` and check that the axis labels in the plot use the attached metadata.

## Saving and Loading DataArrays

### Background

Once data is organized in an Xarray structure, it can easily be saved to disk using scientific file formats such as NetCDF4, which is built on top of the HDF5 storage system. These formats are widely used in scientific computing because they support structured metadata, multidimensional datasets, and efficient storage of large arrays.

Saving data in these formats allows large datasets to be stored and accessed efficiently without requiring them to be fully loaded into memory. It also makes the data portable and accessible to tools outside of Python.

### Exercises

In this section you will save a `DataArray` to a NetCDF file and load it back into memory.

| Code | Description |
| :-- | :-- |
| `Path('data').mkdir(exist_ok=True)` | Create a directory if it does not already exist. |
| `da.to_netcdf('data/file.nc')` | Write a DataArray to a NetCDF file. |
| `xr.load_dataarray('data/file.nc')` | Read a DataArray back into memory from a file. |

**Exercise**: Run the cell below to create a DataArray assigned to a variable `da`. Then, use `da.to_netcdf()` with the `engine='netcdf4'` option to create an HDF5-compatible file called `example.nc`.

In [ ]:
time = xr.DataArray(
    data = np.linspace(0, 100, 30),
    name = 'time',
    dims=['time'],
    attrs = {
        'units': 's',
        'description': 'time samples for each image frame'
    }
)

da = xr.DataArray(
    data=np.random.random(size=(10, 20, 30)),
    name='image',
    dims=['x', 'y', 'time'],
    coords = {
        'time': time,
    },
    attrs = {
        'units': 'brightness',
        'description': 'A generated random image stack',
        'long_name': 'calcium image pixel brightness',
    }
)
da

<xarray.DataArray 'image' (x: 10, y: 20, time: 30)> Size: 48kB
array([[[0.93455784, 0.87070321, 0.25765789, ..., 0.36804857,
         0.20330511, 0.22250059],
        [0.26910653, 0.32319007, 0.61266363, ..., 0.72065349,
         0.69022405, 0.9841665 ],
        [0.30866584, 0.34258123, 0.37106183, ..., 0.87508457,
         0.54426929, 0.53391249],
        ...,
        [0.47750194, 0.09396009, 0.16947604, ..., 0.82964438,
         0.9052506 , 0.70531234],
        [0.28216774, 0.06112643, 0.01806789, ..., 0.38480884,
         0.37651963, 0.15904927],
        [0.54590487, 0.22034884, 0.44358047, ..., 0.56451792,
         0.15344121, 0.47713979]],

       [[0.46278164, 0.37850388, 0.52076647, ..., 0.20957928,
         0.14561883, 0.13893709],
        [0.17786602, 0.05443162, 0.08487059, ..., 0.57080271,
         0.03242944, 0.6644074 ],
        [0.29483855, 0.23221452, 0.77716782, ..., 0.50057916,
         0.49205944, 0.21075994],
...
        [0.73339498, 0.07334617, 0.36866892, ..., 0.23494169,
         0.72033225, 0.56247379],
        [0.885213  , 0.97839821, 0.53160162, ..., 0.91053768,
         0.57536331, 0.37315945],
        [0.58191917, 0.68534983, 0.17020612, ..., 0.87829471,
         0.73874034, 0.41930747]],

       [[0.4606276 , 0.0973907 , 0.70948389, ..., 0.56368729,
         0.74048363, 0.5122833 ],
        [0.45101316, 0.08566925, 0.70246856, ..., 0.47707637,
         0.6644182 , 0.53748297],
        [0.55387455, 0.17310703, 0.72945653, ..., 0.67118948,
         0.71301375, 0.87009826],
        ...,
        [0.32045915, 0.95910132, 0.01923958, ..., 0.52898408,
         0.78974531, 0.96774799],
        [0.86897641, 0.84767354, 0.18733604, ..., 0.14231991,
         0.99106918, 0.37830103],
        [0.40767868, 0.37804333, 0.43709734, ..., 0.4875185 ,
         0.01975035, 0.5726516 ]]], shape=(10, 20, 30))
Coordinates:
  * time     (time) float64 240B 0.0 3.448 6.897 10.34 ... 93.1 96.55 100.0
Dimensions without coordinates: x, y
Attributes:
    units:        brightness
    description:  A generated random image stack
    long_name:    calcium image pixel brightness

In [ ]:
da.to_netcdf('example.nc', engine='netcdf4')

**Exercise**: Open the `example.nc` file in the HDF5 Viewer at https://myhdf5.hdfgroup.org/ to verify it is a valid HDF5 file, and use it to do the following tasks:
  1. View the `time` variable as a line plot.
  2. View the `time` values themselves in a matrix.
  3. View the Image data as a heatmap.
  4. Find the "description" attribute for the `image` variable (hint: check the `inspect` tab)

**Exercise**: Create a `data` directory next to this notebook.

**Exercise**: Run the cell below to create the `eeg` DataArray. Then, save the `eeg` DataArray to `data/eeg.nc`.

In [ ]:
rng = np.random.default_rng(0)
time = np.linspace(0, 2, 1000)
channels = ['Fz', 'Cz', 'Pz', 'Oz']
values = rng.normal(size=(len(channels), len(time)))

eeg = xr.DataArray(
    data=values,
    dims=['channel', 'time'],
    coords={'channel': channels, 'time': time},
    name='eeg',
)
eeg

<xarray.DataArray 'eeg' (channel: 4, time: 1000)> Size: 32kB
array([[ 0.12573022, -0.13210486,  0.64042265, ...,  1.38997173,
        -0.66434209, -0.22997116],
       [ 1.18390191,  0.30382685,  0.19205435, ..., -2.01881162,
        -0.90942756,  0.36922933],
       [ 0.41925483, -0.50224455, -0.85769996, ..., -1.65759515,
        -1.99552682, -0.61334415],
       [-0.38847831, -0.27536744, -1.24011117, ...,  0.55029559,
         0.55104841, -0.8705243 ]], shape=(4, 1000))
Coordinates:
  * channel  (channel) <U2 32B 'Fz' 'Cz' 'Pz' 'Oz'
  * time     (time) float64 8kB 0.0 0.002002 0.004004 ... 1.996 1.998 2.0

**Exercise**: Load `data/eeg.nc` into a new variable and display it to verify that its dimensions, coordinates, and attributes match the original.